//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomePageFeature.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Panel()
        {
            this.PanelElements = new HashSet<PanelElement>();
        }
    
        public int PanelId { get; set; }
        public string Name { get; set; }
        public Nullable<int> LayoutId { get; set; }
        public Nullable<byte> DisplayOrder { get; set; }
    
        public virtual Layout Layout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PanelElement> PanelElements { get; set; }
    }
}
