//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomePageFeature.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelElement
    {
        public int PanelElementId { get; set; }
        public int ElementId { get; set; }
        public string Content { get; set; }
        public int PanelId { get; set; }
    
        public virtual Element Element { get; set; }
        public virtual Panel Panel { get; set; }
    }
}
